name: Deploy via SSH with password

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: deploy
    env:
      SSH_HOST: ${{ vars.SSH_HOST }}
      SSH_USER: ${{ vars.SSH_USER }}
      SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install sshpass
        run: sudo apt-get update && sudo apt-get install -y sshpass

      - name: Add server to known_hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H $SSH_HOST >> ~/.ssh/known_hosts

      - name: Build repo
        run: npm ci && npm run build

      - name: Copy files with password
        run: |
          sshpass -p "$SSH_PASSWORD" scp -r out/* $SSH_USER@$SSH_HOST:www

      - name: Set permissions on remote files
        run: |
          sshpass -p "$SSH_PASSWORD" ssh $SSH_USER@$SSH_HOST "chmod -R 755 www"
